SuperfitApi/SuperfitApi/Controllers/LoginWebController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using SuperfitApi.Models;
using SuperfitApi.Models.Entity;
using SuperfitApi.Controllers;
using System.IO;
using System.Net.Mail;

namespace SuperfitApi.Controllers
{    
    public class LoginWebController : Controller
    {
        #region Variables 
        public SuperfitEntities  Db;
        public Clientes clientes;
        public Cuestionarios cuestionario;
        public Mensualidades mensualidad;
        public Asesoria_antropometria asesoria_antropometria;
        public EnvioNotificaciones envio;
        //modelos
        public ClientesModel clientesMdl;
        public UsuariosModel usuariosMdl;
        public CuestionarioModel cuestionarioMdl;
        public MensualidadModel mensualidadMdl;
        public AntropometriaModel asesoria_antropometriaMdl;
        public AlertasModel alertasMdl;
        #endregion       
        public LoginWebController()
        {
            Db = new SuperfitEntities();
            clientes = new Clientes();
            cuestionario = new Cuestionarios();
            mensualidad = new Mensualidades();
            asesoria_antropometria = new Asesoria_antropometria();
            envio = new EnvioNotificaciones();
            //modelos
            clientesMdl = new ClientesModel();
            usuariosMdl = new UsuariosModel();
            cuestionarioMdl = new CuestionarioModel();
            mensualidadMdl = new MensualidadModel();
            asesoria_antropometriaMdl = new AntropometriaModel();
            alertasMdl = new AlertasModel();
        }        
        public ActionResult Inicio()
        {
            return View();
        }

        // GET: LoginWeb
        public ActionResult LoginWeb()
        {
            try
            {
                var sesion = Session["sesion"];
                if (sesion != null)
                {
                    return RedirectToAction("Perfil", "ClientesWeb");
                }
                else
                {                    
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return View();
            }                       
        }
        [HttpPost]
        public ActionResult LoginWeb(string User, string Pass)
        {
            try
            {
                if (ValidacionUser(User) == true)
                {
                    clientesMdl = (from c in Db.Clientes
                                   where c.Correo_electronico == User
                                   && c.Contraseña == Pass
                                   select new ClientesModel()
                                   {
                                       Id_cliente = c.Id_cliente,
                                       Nombres = c.Nombres,
                                       Foto_perfil = c.Foto_perfil
                                   }).FirstOrDefault();
                }
                else
                {
                    if (ValidarCelular(User) == true)
                    {
                        decimal celular = 0;
                        celular = decimal.Parse(User);
                        clientesMdl = (from c in Db.Clientes
                                       where c.Telefono == celular
                                       && c.Contraseña == Pass
                                       select new ClientesModel()
                                       {
                                           Id_cliente = c.Id_cliente,
                                           Nombres = c.Nombres,
                                           Foto_perfil = c.Foto_perfil
                                       }).FirstOrDefault();
                    }
                    else
                    {
                        clientesMdl = null;
                    }
                }

                if (clientesMdl != null)
                {
                    Session["sesion"] = clientesMdl;
                    Session["Id_cliente"] = clientesMdl.Id_cliente;
                    return RedirectToAction("Perfil", "ClientesWeb");
                }
                else
                {
                    ViewBag.Mensaje = "Usuario y/o contraseña Incorrectos";
                    return View(mensualidadMdl);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Shared", new { Error = ex.Message });
            }
        }
        
        //Administrador        
        public ActionResult LoginAdministradorWeb()
        {
            try
            {
                var sesion = Session["sesion"];
                if (sesion != null)
                {
                    return RedirectToAction("AdministracionWebHome", "AdministracionWebHome");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
                return View();
            }                       
        }
        public ActionResult Recuperarcuenta()
        {
            return View();
        }
        #region Envio de correos
        //Envio de recuperacion cuenta contraseña con codigo aleatorio
        [HttpPost]
        public JsonResult Recuperarcuenta(string User)
        {
            alertasMdl.Result = false;
            bool validacion = false;
            string celortel = string.Empty;
            string succes = string.Empty;
            string pass = string.Empty;
            clientes = new Clientes();
            try
            {
                if (ValidacionUser(User) == true)
                {
                    var clientesserch = Db.Clientes.Where(y => y.Correo_electronico == User).FirstOrDefault();
                    if (clientesserch != null)
                    {
                        pass = clientesserch.Contraseña;
                        celortel = "correo";
                        validacion = true;
                        clientes = clientesserch;
                    }
                    else
                    {
                        alertasMdl.Mensaje = "No se encontro ese usuario con ese correo";
                        alertasMdl.Result = false;
                    }
                }
                else
                {
                    if (ValidarCelular(User) == true)
                    {
                        decimal celular = 0;
                        celular = decimal.Parse(User);
                        var clientesserch = Db.Clientes.Where(y => y.Telefono == celular).FirstOrDefault();
                        if (clientesserch != null)
                        {
                            pass = clientesserch.Contraseña;
                            celortel = "correo";
                            validacion = true;
                            clientes = clientesserch;
                            User = clientesserch.Correo_electronico;
                        }
                        else
                        {
                            alertasMdl.Mensaje = "No se encontro ese usuario con ese numero";
                            alertasMdl.Result = false;
                        }
                    }
                    else
                    {
                        alertasMdl.Mensaje = "No se encontro ese usuario";
                        alertasMdl.Result = false;
                    }
                }

                if (validacion == true)
                {
                    string codigo = envio.GenerarCodigo();
                    clientes.Contraseña = codigo;
                    Db.SaveChanges();
                    if (celortel == "correo")
                    {
                        //
                        Dictionary<string, string> datoscorreo = new Dictionary<string, string>();
                        datoscorreo.Add("@CodigoRecuperacion", codigo);
                        string plantilla = Server.MapPath("~/Plantillas/CorreoRecuperacion.html");
                        succes = "Revisa tu correo que proporcionaste para continuar";
                        string asunto = "Recuperar contraseña";
                        AlertasModel resultado = envio.EnviarCorreo(User, plantilla, datoscorreo, succes, asunto);
                        if (resultado.Result == false)
                        {
                            clientes.Contraseña = pass;
                            Db.SaveChanges();
                        }
                        alertasMdl = resultado;                    
                    }
                    else
                    {
                        succes= "Revisa tu whatsapp con el numero proporcionaste para continuar";
                        string Mensaje = string.Empty;                       
                        Mensaje = "Codigo de recuperacion\n";
                        Mensaje += "Introduce este código autogenerado como contraseña temporal,\ndespues que inicies sesion cambia tu contraseña\n";
                        Mensaje += codigo;
                        Mensaje += "\nLos códigos de caducan después de dos horas.\n";
                        Mensaje += "Ir a Superfit\n";
                        Mensaje += "https://www.bsite.net/valerioparada";
                        AlertasModel resultado = envio.EnviarMensaje(User, Mensaje, succes);
                        if (resultado.Result == false)
                        {
                            clientes.Contraseña = pass;
                            Db.SaveChanges();
                        }
                        alertasMdl = resultado;
                    }

                }
                else
                {

SuperfitApi/SuperfitApi/Views/LoginWeb/LoginAdministradorWeb.cshtml
<!DOCTYPE html>
@{
    Layout = null;
}
<html>
<head>
    <title>Superfit Administrador Web </title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/datatablescss")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")
<link rel="shortcut icon" type="image/png" href="https://superflyfit.000webhostapp.com/imagenes/superfiticono.jpeg" />
    <style>
        .login {
            margin-top: 10px;
            text-align: center;
        }

        .row {
            margin-top: 10px;
        }

        .card {
            margin-top: 100px;
            width: 400px;
            height: 500px;
            border-color: black;
            border-style: solid;
            border-width: 1px 1px 1px 1px;
            border-radius: 20px 20px;
        }

        .card-header {
            background-color: transparent;
            border-color: transparent;
        }

        .card-body {
            background-color: transparent;
            margin-top: 50px;
        }

        .card-footer {
            margin-top: 50px;
            border-color: transparent;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg" style="background-color:#007bff">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler btn btn-outline-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="fa fa-navicon"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Inicio", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Home</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("RegistrarCliente", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Registrarse</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("LoginWeb", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Inicio sesión</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <div class="col-12 text-center">
                    <h3 style="color:#007bff">
                        Superfit para administradores
                    </h3>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("LoginAdministradorWeb", "LoginWeb", FormMethod.Post, new { @id = "FormLogin" }))
                {
                    <form>
                        <div class="row">
                            <div class="col">
                                @Html.TextBox("User", null, new { @class = "form-control", id = "User", placeholder = "Correo eléctronico o celular", style = "color:black;border-color:#007bff" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                @Html.TextBox("Pass", null, new { @class = "form-control", id = "Pass", type = "password", placeholder = "Contraseña", style = "color:black;border-color: #007bff" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" id="Iniciarsesion" class="form-control btn btn-primary" style="background-color: #007bff">Iniciar sesión</button>
                            </div>
                        </div>
                        <hr />
                        <div class="login">
                            @Html.ActionLink("Soy un cliente", "LoginWeb", "LoginWeb", new { @class = "btn-link" })
                        </div>
                        <div class="login">
                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="text-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</body>
</html>

SuperfitApi/SuperfitApi/Views/LoginWeb/LoginWeb.cshtml
<!DOCTYPE html>
@{
    Layout = null;
}
<html>
<head>
    <title>Superfit</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/datatablescss")
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="stylesheet" type="text/Content" href="https://cdn.datatables.net/1.10.24/Content/jquery.dataTables.Content">

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert-dev.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.Content">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="https://superflyfit.000webhostapp.com/imagenes/superfiticono.jpeg" style="width: 20em;" />
    <style>
        .login {
            margin-top: 10px;
            text-align: center;
        }

        .row {
            margin-top: 10px;
        }

        .card {
            margin-top: 100px;
            width: 400px;
            height: 500px;
            border-color: black;
            border-style: solid;
            border-width: 1px 1px 1px 1px;
            border-radius: 20px 20px;
        }

        .card-header {
            background-color: transparent;
            border-color: transparent;
        }

        .card-body {
            background-color: transparent;
            margin-top: 50px;
        }

        .card-footer {
            margin-top: 50px;
            border-color: transparent;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg" style="background-color:#007bff">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler btn btn-outline-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="fa fa-navicon"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Inicio", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Home</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("RegistrarCliente", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Registrarse</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("LoginWeb", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Inicio sesión</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <div class="col-12 text-center">
                    <h3 style="color:#007bff">
                        Superfit
                    </h3>
                </div>
            </div>
            <div class="card-body">
                @using (Html.BeginForm("LoginWeb", "LoginWeb", FormMethod.Post, new { @id = "FormLogin" }))
                {
                    <form>
                        <div class="row">
                            <div class="col">
                                @Html.TextBox("User", null, new { @class = "form-control", id = "User", placeholder = "Correo eléctronico o celular", style = "color:black;border-color:#007bff" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                @Html.TextBox("Pass", null, new { @class = "form-control", id = "Pass", type = "password", placeholder = "Contraseña", style = "color:black;border-color: #007bff" })
                            </div>
                        </div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" id="Iniciarsesion" class="form-control btn btn-primary" onclik="document.body.style.cursor='wait';" style="background-color: #007bff">Iniciar sesión</button>
                            </div>
                        </div>
                        <div class="login">
                            @Html.ActionLink("¿Olvidaste tu contraseña?", "Recuperarcuenta", "LoginWeb", new { @class = "btn-link" })
                        </div>
                        <hr />
                        <div class="login">
                            @Html.ActionLink("Registrarse", "RegistrarCliente", "LoginWeb", new { @class = "btn btn-success" })
                        </div>
                        <div class="login">
                            @Html.ActionLink("Soy un administrador", "LoginAdministradorWeb", "LoginWeb", new { @class = "btn-link" })
                        </div>
                        <div class="login">
                            @if (ViewBag.Mensaje != null)
                            {
                                <div class="text-danger">
                                    @ViewBag.Mensaje
                                </div>
                            }
                        </div>
                    </form>
                }
            </div>
        </div>
    </div>
</body>
</html>

SuperfitApi/SuperfitApi/Views/LoginWeb/Recuperarcuenta.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Recuperar cuenta</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/fontawesome")
    @Styles.Render("~/bundles/datatablescss")

    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.css">

    <script src="https://code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="~/scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/scripts/bootstrap.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert-dev.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <link rel="shortcut icon" type="image/png" href="https://superflyfit.000webhostapp.com/imagenes/superfiticono.jpeg" />
    <style>
        .login {
            margin-top: 10px;
            text-align: center;
        }

        .row {
            margin-top: 10px;
        }

        .card {
            margin-top: 100px;
            width: 400px;
            height: 500px;
            border-color: black;
            border-style: solid;
            border-width: 1px 1px 1px 1px;
            border-radius: 20px 20px;
        }

        .card-header {
            background-color: transparent;
            border-color: transparent;
        }

        .card-body {
            background-color: transparent;
            margin-top: 50px;
        }

        .card-footer {
            margin-top: 50px;
            border-color: transparent;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg" style="background-color:#007bff">
            <a class="navbar-brand" href="#"></a>
            <button class="navbar-toggler btn btn-outline-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"><i class="fa fa-navicon"></i></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("Inicio", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Home</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("RegistrarCliente", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Registrarse</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="navbar-brand" href="@Url.Action("LoginWeb", "LoginWeb", null, null)">
                            <span class="menu-collapsed text-white">Inicio sesión</span>
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="d-flex justify-content-center h-100">
        <div class="card">
            <div class="card-header">
                <div class="col-12 text-center">
                    <h3 style="color:#007bff">
                        Superfit
                    </h3>
                </div>
            </div>
            <div class="card-body">
                <div>
                    <div class="row">
                        <div class="col">
                            <h6>
                                Ingresa tu correo electrónico,
                                teléfono y te enviaremos un enlace para que recuperes el acceso a tu cuenta.
                            </h6>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            @*@Html.TextBox("User", null, new { @class = "form-control", id = "User", placeholder = "Correo eléctronico o celular", style = "color:black;border-color:#007bff" })*@
                            <input type="text" id="cuenta" class="form-control" placeholder="Correo electronico o Telefono" style="color:black;border-color:#007bff" />
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <button type="button" id="enviar" class="form-control btn btn-primary" onclick="Enviar();" style="background-color: #007bff">Aceptar</button>
                        </div>
                    </div>
                    <div class="login">
                        @Html.ActionLink("Regresar", "LoginWeb", "LoginWeb", new { @class = "btn-link" })
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
<script type="text/javascript">
    function Enviar() {        
            var usuario = document.getElementById("cuenta").value;
            var urlgenerar = '@Url.Action("Recuperarcuenta", "LoginWeb")';
            $.ajax({
                type: "POST",
                url: urlgenerar,
                data: { "user": usuario },
                datatype: "json",
                success: function (valor) {
                    if (valor["Result"] == true) {                        
                        swal({
                            title: "Éxito",
                            text: valor["Mensaje"],
                            type: "success"
                        });
                    }
                    else {
                        swal({
                            title: "Error",
                            text: valor["Mensaje"],
                            type: "warning"
                        });
                    }
                },
                error: function (xhr, status, error) {
                    console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText);                    
                    swal("Warning", "No se realizo la conexion intente de nuevo, warning:" + error +",warning");
                }
            });
        }
</script>