SuperfitApi/SuperfitApi/Controllers/AdministracionWeb/AdministracionWebHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using SuperfitApi.Models.Entity;
using SuperfitApi.Models;
using System.Web.Mvc;
using System.IO;
using SuperfitApi.Autetication;
using System.Globalization;
using System.Net.Mail;

namespace SuperfitApi.Controllers.AdministracionWeb.CatalogosWeb
{
    [Validation]
    public class AdministracionWebHomeController : Controller
    {
        #region Variables
        public SuperfitEntities Db;
        public Clientes clientes;
        public Cuestionarios cuestionario;
        public Mensualidades mensualidad;
        public Asesoria_antropometria asesoria_antropometria;
        public Tipo_rutinas tipo_Rutina;
        public Tipo_entrenamientos tipo_Entrenamiento;
        public Ejercicios ejercicios;
        public Estatus estatus;
        public Rutinas rutina;
        public Detalle_rutinas detalle_Rutina;
        public List<Detalle_rutinas> listdetalle_Rutina;
        public EnvioNotificaciones envio;
        //modelos
        public AlertasModel alertasMdl;

        public ClientesModel clientesMdl;
        public CuestionarioModel cuestionarioMdl;
        public MensualidadModel mensualidadMdl;
        public AntropometriaModel asesoria_antropometriaMdl;
        public TiporutinaModel tiporutinaMdl;
        public TipoentrenamientoModel tipoentrenamientoMdl;
        public EjerciciosModel ejerciciosMdl;
        public EstatusModel estatusMdl;
        public AntropometriaModel antropometriaMdl;
        public RutinasModel rutinasMdl;
        public DetallerutinaModel detallerutinaMdl;


        //listas 
        public List<ClientesModel> listclientesMdl;
        public List<MensualidadModel> listmensualidadMdl;
        public List<TiporutinaModel> listtiporutinaMdl;
        public List<TipoentrenamientoModel> listtipoentrenamientoMdl;
        public List<EjerciciosModel> listejerciciosMdl;
        public List<EstatusModel> listestatusMdl;
        public List<AntropometriaModel> listantropometriaMdl;
        public List<RutinasModel> listrutinasMdl;
        public List<MesesModel> listmesesMdl;
        public List<DetallerutinaModel> listdetallerutinaMdl;

        #endregion
        public AdministracionWebHomeController()
        {
            Db = new SuperfitEntities();
            clientes = new Clientes();
            cuestionario = new Cuestionarios();
            mensualidad = new Mensualidades();
            asesoria_antropometria = new Asesoria_antropometria();
            tipo_Rutina = new Tipo_rutinas();
            tipo_Entrenamiento = new Tipo_entrenamientos();
            ejercicios = new Ejercicios();
            rutina = new Rutinas();
            detalle_Rutina = new Detalle_rutinas();
            listdetalle_Rutina = new List<Detalle_rutinas>();
            envio = new EnvioNotificaciones();
            //modelos
            clientesMdl = new ClientesModel();
            cuestionarioMdl = new CuestionarioModel();
            mensualidadMdl = new MensualidadModel();
            asesoria_antropometriaMdl = new AntropometriaModel();
            alertasMdl = new AlertasModel();
            tiporutinaMdl = new TiporutinaModel();
            tipoentrenamientoMdl = new TipoentrenamientoModel();
            ejerciciosMdl = new EjerciciosModel();
            estatusMdl = new EstatusModel();
            antropometriaMdl = new AntropometriaModel();
            detallerutinaMdl = new DetallerutinaModel();
            

            //listas
            listclientesMdl = new List<ClientesModel>();
            listmensualidadMdl = new List<MensualidadModel>();
            listtiporutinaMdl = new List<TiporutinaModel>();
            listtipoentrenamientoMdl = new List<TipoentrenamientoModel>();
            listejerciciosMdl = new List<EjerciciosModel>();
            listestatusMdl = new List<EstatusModel>();
            listantropometriaMdl = new List<AntropometriaModel>();
            listrutinasMdl = new List<RutinasModel>();
            listmesesMdl = new List<MesesModel>();
            listdetallerutinaMdl = new List<DetallerutinaModel>();
        }
        // GET: AdministracionWebHome
        public ActionResult AdministracionWebHome()
        {
            List<ClientesModel> pendientes = new List<ClientesModel>();
            List<ClientesModel> activos = new List<ClientesModel>();
            List<ClientesModel> inactivos = new List<ClientesModel>();
            List<ClientesModel> porfinalizar = new List<ClientesModel>();

            listclientesMdl = (from l in Db.Clientes
                               select new ClientesModel()
                               {
                                   Id_cliente = l.Id_cliente,
                                   Clave_cliente = l.Clave_cliente,
                                   Nombres = l.Nombres,
                                   Apellido_paterno = l.Apellido_paterno,
                                   Apellido_materno = l.Apellido_materno,
                                   Apodo = l.Apodo,
                                   Edad = l.Edad,
                                   Telefono = (decimal)l.Telefono,
                                   Correo_electronico = l.Correo_electronico,
                                   Estado = (bool)l.Estado,
                                   Contraseña = l.Contraseña,
                                   Foto_perfil = l.Foto_perfil,
                                   Sexo = l.Sexo
                               }).ToList();

            listmensualidadMdl = (from m in Db.Mensualidades
                                  join c in Db.Clientes
                                  on m.Id_cliente equals c.Id_cliente                                  
                                  join es in Db.Estatus
                                  on m.Id_estatus equals es.Id_estatus                                  
                                  select new MensualidadModel()
                                  {
                                      Id_mensualidad = m.Id_mensualidad,
                                      Fecha_inicio = (DateTime)m.Fecha_inicio,
                                      Fecha_fin = (DateTime)m.Fecha_fin,
                                      Estatus = new EstatusModel
                                      {
                                          Id_estatus = es.Id_estatus,
                                          Descripcion = es.Descripcion
                                      },
                                      Cliente = new ClientesModel
                                      {
                                          Id_cliente = c.Id_cliente,
                                          Clave_cliente = c.Clave_cliente,
                                          Nombres = c.Nombres,
                                          Apellido_paterno = c.Apellido_paterno,
                                          Apellido_materno = c.Apellido_materno,
                                          Apodo = c.Apodo,
                                          Edad = c.Edad,
                                          Telefono = (decimal)c.Telefono,
                                          Correo_electronico = c.Correo_electronico,
                                          Estado = (bool)c.Estado,
                                          Contraseña = c.Contraseña,
                                          Foto_perfil = c.Foto_perfil,
                                          Sexo = c.Sexo
                                      }
                                  }).ToList();

            if (listclientesMdl.Count > 0)
            {
                foreach(ClientesModel cliente in listclientesMdl)
                {             
                    if (listmensualidadMdl.Count > 0)
                    {
                        var list = listmensualidadMdl.Where(y => y.Cliente.Id_cliente == cliente.Id_cliente).ToList();
                        var mensualidad = list.OrderByDescending(p => p.Fecha_fin).FirstOrDefault();
                        if (mensualidad != null)
                        {
                            if (mensualidad.Estatus.Id_estatus == 1)
                            {
                                pendientes.Add(cliente);
                            }
                            else if (mensualidad.Estatus.Id_estatus == 2 || mensualidad.Estatus.Id_estatus == 4)
                            {
                                activos.Add(cliente);
                            }
                            else
                            {
                                inactivos.Add(cliente);
                            }
                        }
                    }
                    if (cliente != null)
                    {
                        var list = listmensualidadMdl.Where(y => y.Cliente.Id_cliente == cliente.Id_cliente).ToList();
                        if (list.Count == 0)
                        {
                            pendientes.Add(cliente);
                        }                        
                    }
                }

                if(listmensualidadMdl.Count > 0)
                {                    
                    var finalizar = listmensualidadMdl.Where(y => (y.Estatus.Id_estatus == 2 || y.Estatus.Id_estatus == 4) && DateTime.Now.AddDays(5) >= y.Fecha_fin).ToList();
                    if(finalizar.Count > 0)
                    {
                        foreach(MensualidadModel mes in finalizar)
                        {
                            if((mes.Fecha_fin < DateTime.Now) && (mes.Estatus.Id_estatus == 2 || mes.Estatus.Id_estatus == 4))
                            {
                                mensualidad = Db.Mensualidades.Where(y => y.Id_mensualidad == mes.Id_mensualidad).FirstOrDefault();
                                if (mensualidad != null)
                                {

SuperfitApi/SuperfitApi/Views/AdministracionWebHome/AdminAsesoriaantropometriaWeb.cshtml
@using SuperfitApi.Models
@model List<AntropometriaModel>

@{
    Layout = "~/Views/Shared/DiseñoAdmin.cshtml";
}

<div id="content">
    <div class="container-fluid">
        <h3><i class="fa fa-address-book"></i> Asesoria antropometria </h3>
        <hr id="line" />
        <span class="float-right" style="margin-top:-65px">
            <button type="button" class="btn btn-primary" onclick="Ver()">Nuevo Asesoria antropometria</button>
        </span>
        <br />
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-hover" id="tabla">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Editar</th>
                        <th>Clave entrenamiento</th>
                        <th>Tipo entrenamiento</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id</td>
                            <td><button type="button" class="btn btn-primary fa fa-pencil" onclick="VerEditar(@item.Id)"></button></td>
                            <td>@item.Peso</td>
                            <td>@item.Altura</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--MODAL PARA Agregar--->
<div class="modal fade" id="ModalAgregar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLongTitle">Nuevo Asesoria antropometria</h3>
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdNombre" placeholder="Nombre(s)" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                    <br />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Agregar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!--MODAL PARA Editar--->
<div class="modal fade" id="ModalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLongTitle">Asesoria antropometria</h3>
                <h5></h5>
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <input id="id" style="display:none" />
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdNombreE" placeholder="Nombre(s)" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                    <br />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" onclick="Editar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">

    var url = '@Url.Action("AgregarCliente", "AdministracionWebHome")';
    var urleditar = '@Url.Action("EditarCliente", "AdministracionWebHome")';

    function Ver() {
        $('#ModalAgregar').modal('show');
    }

    function Agregar() {

    }

    function VerEditar(Id) {

    }

    function Editar() {
    }

</script>

SuperfitApi/SuperfitApi/Views/AdministracionWebHome/AdminEstatusWeb.cshtml
@using SuperfitApi.Models
@model List<EstatusModel>

@{
    Layout = "~/Views/Shared/DiseñoAdmin.cshtml";
}

<div id="content">
    <div class="container-fluid">
        <h3 class="letracolor"><i class="fa fa-address-book"></i> Estatus</h3>
        <hr id="line" />
        <span class="float-right" style="margin-top:-65px">
            <button type="button" class="color btn btn-primary" onclick="Ver()">Nuevo Estatus</button>
        </span>
        <br />
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-hover" id="tablaestatus">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Editar</th>
                        <th>Descripcion </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id_estatus</td>
                            <td><button type="button" class="color btn btn-primary fa fa-pencil" onclick="VerEditar(@item.Id_estatus)"></button></td>                          
                            <td>@item.Descripcion</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--MODAL PARA Agregar--->
<div class="modal fade" id="ModalAgregar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="letracolor modal-title" id="exampleModalLongTitle">Nuevo Estatus</h3>
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdDescripcion" placeholder="Descripcion" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                    <br />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="color btn btn-primary" onclick="Agregar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!--MODAL PARA Editar--->
<div class="modal fade" id="ModalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="letracolor modal-title" id="exampleModalLongTitle">Estatus</h3>
                <h5></h5>
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <input id="idvalue" style="display:none" />
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdDescripcionE" placeholder="Descripcion" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                    <br />
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="color btn btn-primary" onclick="Editar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#tablaestatus').DataTable();
    });
    var url = '@Url.Action("AgregarEstatus", "AdministracionWebHome")';
    var urleditar = '@Url.Action("EditarEstatus", "AdministracionWebHome")';

    function Ver() {
        $('#ModalAgregar').modal('show');
    }

    function Agregar() {
        var parametros = {};
        parametros.Descripcion = $("#IdDescripcion").val().trim();
        var model = parametros;
        if (parametros.descripcion != "")
        {
            $.ajax({
                type: "POST",
                url: url,
                data: model,
                success: function (data) {
                    if (data == "True") {
                        location.reload();
                    }
                    else {
                        location.reload();
                    }
                },
                error: function (xhr, status, error) {
                    console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                    alert("Ocurrio un error verifique su conexion");
                }
            });
        }
        else
        {
            document.getElementById("IdDescripcion").style.borderColor = "red";
        }
    }

    function VerEditar(Id)
    {
        $.ajax({
            type: "GET",
            url: urleditar,
            data: { "Id_estatus": Id },
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            success: function (data) {
                document.getElementById('idvalue').value = data["Id_estatus"];
                document.getElementById("IdDescripcionE").value = data["Descripcion"];                
                $('#ModalEditar').modal('show');
            },
            error: function (xhr, status, error) {
                console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                alert("Ocurrio un error verifique su conexion");
            }
        });
    }

    function Editar()
    {
        var parametros = {};
        parametros.Id_estatus = $("#idvalue").val().trim();
        parametros.Descripcion = $("#IdDescripcionE").val().trim();
        var model = parametros;
        if (parametros.descripcion != "")
        {
            $.ajax({
                type: "POST",
                url: urleditar ,
                data: model,
                success: function (data) {
                    if (data == "True") {
                        location.reload();
                    }
                    else {
                        location.reload();
                    }
                },
                error: function (xhr, status, error) {
                    console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                    alert("Ocurrio un error verifique su conexion");
                }
            });
        }
        else
        {
            document.getElementById("IdDescripcionE").style.borderColor = "red";
        }
        
    }

</script>

SuperfitApi/SuperfitApi/Views/AdministracionWebHome/AdminRutinasWeb.cshtml
@using SuperfitApi.Models
@model List<RutinasModel>

@{
    Layout = "~/Views/Shared/DiseñoAdmin.cshtml";
}

<div id="content">
    <div class="container-fluid">
        <h3 class="letracolor"><i class="fa fa-address-book"></i> Rutinas </h3>
        <hr id="line" />
        <span class="float-right" style="margin-top:-65px">
            <button type="button" class="color btn btn-primary" onclick="Ver()">Nuevo Rutina</button>
        </span>
        <br />
        <div class="table-responsive">
            <table class="table table-condensed table-striped table-hover" id="tablarutina">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Editar</th>
                        <th>Clave rutina</th>
                        <th>Descripcion</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.Id_rutina</td>
                            <td><button type="button" class="color btn btn-primary fa fa-pencil" onclick="VerEditar(@item.Id_rutina)"></button></td>
                            <td>@item.Clave_rutina</td>
                            <td>@item.Descripcion</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--MODAL PARA Agregar--->
<div class="modal fade" id="ModalAgregar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="letracolor modal-title" id="exampleModalLongTitle">Nueva Rutina</h3>
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdClaverutina" placeholder="Clave rutina" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdDescripcion" placeholder="Descripcion" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="color btn btn-primary" onclick="Agregar()">Guardar</button>
            </div>
        </div>
    </div>
</div>

<!--MODAL PARA Editar--->
<div class="modal fade" id="ModalEditar" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="letracolor modal-title" id="exampleModalLongTitle">Rutina</h3>
                <h5></h5>
                <button type="button" class="btn btn-danger" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="container">
                    <input id="idvalue" style="display:none" />
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdClaverutinaE" placeholder="Clave rutina" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                    <br />
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <input type="text" class="form-control" id="IdDescripcionE" placeholder="Descripcion" onkeypress="style.borderColor='gray'" />
                        </div>
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                <button type="button" class="color btn btn-primary" onclick="Editar()">Guardar</button>
            </div>
        </div>
    </div>
</div>


<script src="js/jquery.min.js" type="text/javascript"></script>
<script src="js/jquery.dataTables.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#tablarutina').DataTable();
    });

    var url = '@Url.Action("AgregarRutinas", "AdministracionWebHome")';
    var urleditar = '@Url.Action("EditarRutinas", "AdministracionWebHome")';

    function Ver() {
        $('#ModalAgregar').modal('show');
    }

    function Agregar() {
        var parametros = {};
        parametros.Clave_rutina = $('#IdClaverutina').val().trim();
        parametros.Descripcion = $('#IdDescripcion').val().trim();
        var model = parametros;

        if (parametros.Clave_rutina != "")
        {
            if (parametros.Descripcion != "")
            {
                $.ajax({
                    type: "POST",
                    url: url,
                    data: model,
                    success: function (data) {
                        if (data == "True") {
                            location.reload();
                        }
                        else {
                            location.reload();
                        }
                    },
                    error: function (xhr, status, error) {
                        console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                        alert("Ocurrio un error verifique su conexion");
                    }
                });
            }
            else {
                document.getElementById("IdDescripcion").style.borderColor = "red";
            }
        }
        else {
            document.getElementById("IdClaverutina").style.borderColor = "red";
        }
    }

    function VerEditar(Id) {
        $.ajax({
            type: "GET",
            url: urleditar,
            data: { "Id_rutina": Id },
            contentType: "application/json; charset=utf-8",
            datatype: "json",
            success: function (data) {
                document.getElementById('idvalue').value = data["Id_rutina"];
                document.getElementById('IdClaverutinaE').value = data["Clave_rutina"];
                document.getElementById('IdDescripcionE').value = data["Descripcion"];
                $('#ModalEditar').modal('show');
            },
            error: function (xhr, status, error) {
                console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                alert("Ocurrio un error verifique su conexion");
            }
        });
    }

    function Editar()
    {
        var parametros = {};
        parametros.Id_rutina = $('#idvalue').val().trim();
        parametros.Clave_rutina = $('#IdClaverutinaE').val().trim();
        parametros.Descripcion = $('#IdDescripcionE').val().trim();
        var model = parametros;

        if (parametros.Clave_rutina != "")
        {
            if (parametros.Descripcion != "")
            {
                $.ajax({
                    type: "POST",
                    url: urleditar,
                    data: model,
                    success: function (data) {
                        if (data == "True") {
                            location.reload();
                        }
                        else {
                            location.reload();
                        }
                    },
                    error: function (xhr, status, error) {
                        console.log("Result: " + status + " " + error + " " + xhr.status + " " + xhr.statusText)
                        alert("Ocurrio un error verifique su conexion");
                    }
                });
            }
            else {
                document.getElementById("IdClaverutinaE").style.borderColor = "red";
            }
        }
        else {
            document.getElementById("IdDescripcionE").style.borderColor = "red";
        }
    }

</script>